---
title: "viz_part_2"
author: "kindle zhang"
date: "2023-10-03"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
library(ggridges)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.4,
  out.width = "90%"
)
```

This results in a dataframe with `r nrow(weather_df)` observations on six variables
## viz

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

## some plot from last 

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name))+     geom_point(alpha = .5)+
  labs(
    title = "Temerpature plot",
    x = "min",
    y = "max",
    color = "Location",
    caption = "Max vs Min"
  ) +
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15 c", "0", "15")
  ) +
  scale_y_continuous(
    position = "right",
    limits = c(20,30)
  )
```
## 2

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name))+     geom_point(alpha = .5)+
  labs(
    title = "Temerpature plot",
    x = "min",
    y = "max",
    color = "Location",
    caption = "Max vs Min"
  ) + 
  # scale_color_hue(h = c(150, 300))
  viridis::scale_color_viridis(discrete = TRUE)+
  theme(legend.position = "bottom")
   + theme_minimal() # theme_bw
```

## "patchwork"

```{r}
weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  facet_grid(. ~ name)
```

```{r}
ggp_temp_scatter =
  weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  theme(legend.position = "none")

ggp_prcp_density = 
  weather_df |> 
  filter(prcp > 25) |> 
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = .5) + 
  theme(legend.position = "bottom")

ggp_tmax_date = 
  weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name))+
  geom_point(alpha = .5) + 
  geom_smooth(se = FALSE) + 
  theme(legend.position = "bottom")
  
(ggp_temp_scatter + ggp_prcp_density) / ggp_tmax_date
```

## box plot

```{r}
weather_df |> 
  mutate(
    name = fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))
  ) |> 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()

weather_df |> 
  mutate(
    name = fct_reorder(name, tmax, .na_rm = FALSE)
  ) |> 
  ggplot(aes(x = name, y = tmax, fill = name)) +
  geom_violin()
```

## complicated FAS plot

```{r}
litters_df =
  read_csv("FAS_litters.csv") |> 
  janitor::clean_names() |> 
  separate(group, into = c("dose", "day_of_tx"), sep = 3)

pups_df = 
  read_csv("FAS_pups.csv") |> 
  janitor::clean_names()

fas_df = 
  left_join(pups_df, litters_df, by = "litter_number") |> 
  select(dose, day_of_tx, starts_with("pd")) |> 
  pivot_longer(
    pd_ears:pd_walk,
    names_to = "outcome",
    values_to = "pn_day"
  ) |> 
  drop_na() |> 
  mutate(outcome, fct_reorder(outcome, pn_day)) |> 
  ggplot(aes(x = dose, y = pn_day))+
  geom_violin() +
  facet_grid(day_of_tx ~ outcome)
```

